config/routes.rb
HMS3::Application.routes.draw do
  
root to: "preferences#message_times"

  resources :preferences
    
  resources :welcome

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  
  # attr_accessible :title, :body
end

app/models/customer_profile.rb
class CustomerProfile < ActiveRecord::Base
  attr_accessible :customer_name, :start_date, :customer_name, :start_date, :renewal_date, :primary_contact_email, 
  :secondary_contact_email, :phone_contact, :fax_contact, :street, :city, :state,
   :zip, :customer_type, :caseload_maximum, :active
  
  
  has_one :preferences
  
  after_create :initialize_customer_profile


#protected
  def initialize_customer_profile
  #puts "saved"  
    
    Preferences.create!({voice: true, text: true, email: true, msg_pref: "Send Just Texts" })
    


  
   end
 end
 
 

app/models/preference.rb
class Preference < ActiveRecord::Base
  attr_accessible :email, :msg_pref, :text, :voice, :timezone
  belongs_to :customer_profile
  

end

app/models/preferences.rb
class Preferences < ActiveRecord::Base
  attr_accessible :voice, :text, :email, :msg_pref, :timezone
  belongs_to :customer_profile
  #validates :customer_id, presence: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  #  before_filter :set_timezone

  #  private

    #def set_timezone
    #  tz = current_preferences ? current_preferences.timezone : nil
    #  Time.zone = tz || ActiveSupport::TimeZone["London"]
    end

app/controllers/preferences_controller.rb
class PreferencesController < InheritedResources::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>

<head>
	<title>Health Messaging System</title>
    <!--[if lt IE 9]>
       <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
     <![endif]-->
     <%= stylesheet_link_tag    "application", :media => "all" %>
     <%= javascript_include_tag "application" %>
     <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
   
  
  
  
   
   <div class="container-fluid">
     <div class="row-fluid">

       <div class="span2">
		  <br> 
  	     <div style="text-align: center">
   
  	  	<img src="/teletasklogo.jpg" alt="logo"  >  </td>
  
  	    </div> 
		
		<hr>
		
         <!--Sidebar content-->
		 
		<a class="btn-navbar' data-toggle="collapse" data-taget=".nav-collapse"
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			
			</a>
			<a class="brand" href="#"></a>
			
			
			  
			
			
			<div class="nav-collapse">
				
				  
				<ul class="nav nav-list">
			    <li class="active">
				<a href="/Dashboard"><h4><i class="icon-th-large"></i> Dashboard</h4></a></li>
						<li class="divider"></li>
				
				<li><a href="#Messages"><h4><i class="icon-comment"></i> Messages</h4></a></li>
					<li class="divider"></li>
				
				<li><a href="#Participants"><h4><i class="icon-user"></i> Participants</h4></a></li>
					<li class="divider"></li>
				
				<li><a href="#Reports"><h4><i class="icon-list-alt"></i> Reports</h4></a></li>
					<li class="divider"></li>
			    
				<li><a href="#Settings"><h4><i class="icon-wrench"></i> Settings</h4></a></li>
						<li class="divider"></li>
				  </ul>
		
			
		
			
				
			</div>
		 
       </div>
       <div class="span10">
         <!--Body content-->
	
			
			<div class="container">
			 	<div class="row">
					<br>
						
					<ul class="inline">
					<%= yield %>
					<li>
			</div>
			
	
		 
		 
		 
       </div>
   </div>
</div>

		
			

</body>

</html>

app/views/layouts/preferences.html.erb
<!DOCTYPE html>


<html>

<head>
	<title>Health Messaging System</title>
    <!--[if lt IE 9]>
       <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
     <![endif]-->
     <%= stylesheet_link_tag    "application", :media => "all" %>
     <%= javascript_include_tag "application" %>
     <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
   
  
  
  
   
   <div class="container-fluid">
     <div class="row-fluid">

       <div class="span2">
		  <br> 
  	     <div style="text-align: center">
   
  	  	<img src="/teletasklogo.jpg" alt="logo"  >  </td>
  
  	    </div> 
		
		<hr>
		
         <!--Sidebar content-->
		 
		<a class="btn-navbar' data-toggle="collapse" data-taget=".nav-collapse"
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			
			</a>
			<a class="brand" href="#"></a>
			
			
			  
			
			
			<div class="nav-collapse">
				
				  
				<ul class="nav nav-list">
			   
				<li><a href="/Dashboard"><h4><i class="icon-th-large"></i> Dashboard</h4></a></li>
						<li class="divider"></li>
				
				<li><a href="#Messages"><h4><i class="icon-comment"></i> Messages</h4></a></li>
						<li class="divider"></li>
				
				<li><a href="#Participants"><h4><i class="icon-user"></i> Participants</h4></a></li>
					<li class="divider"></li>
				
				<li><a href="#Reports"><h4><i class="icon-list-alt"></i> Reports</h4></a></li>
					<li class="divider"></li>
			    
				<li class="active"><a href="#Settings"><h4><i class="icon-wrench"></i> Settings</h4></a></li>
						<li class="divider"></li>
				  </ul>
		
			
		
			
				
			</div>
		 
       </div>
       <div class="span10">
         <!--Body content-->
	
			
			<div class="container">
			 	<div class="row">
					<br>
						
					<ul class="inline">
					<%= yield %>
					<li>
			</div>
			
	
		 
		 
		 
       </div>
   </div>
</div>

		
			

</body>

</html>

app/views/preferences/_form.html.erb
<%= semantic_form_for @preference do |f| %>
  <%= f.inputs do %>
    <%= f.input :voice %>
    <%= f.input :text %>
    <%= f.input :email %>
  
	<%= f.select :msg_pref, [['Send All Message Types','all'],['Send Just Texts','text'],['Send Just Voice Calls','voice'],['Send Just Emails','email']] %>
	
	  
	
	    <%= f.label :timezone %>
	
		<%= f.collection_select :timezone, ActiveSupport::TimeZone.us_zones, :name, :to_s %>
	  
		<h3>Selet Do Not Contact days of the year</h3>
	   
	    <%= f.input :holiday_new_year %> 
	    <%= f.input :holiday_martin_luther_king_jr %> 
	    <%= f.input :holiday_presidents %> 
	    <%= f.input :holiday_memorial %> 
	    <%= f.input :holiday_independence %> 
	    <%= f.input :holiday_labor %> 
	    <%= f.input :holiday_columbus %> 
	    <%= f.input :holiday_veterans %> 
	    <%= f.input :holiday_thanksgiving %> 
	    <%= f.input :holiday_christmas %> 
	  
	    t.date     "added_holiday_1"
	    t.date     "added_holiday_2"
	    t.date     "added_holiday_3"
	    t.date     "added_holiday_4"
	    t.date     "added_holiday_5"
	    t.date     "added_holiday_6"
	    t.date     "added_holiday_7"
	    t.boolean  "sunday_send",                   :default => true
	    t.time     "sunday_start",                  :default => '2000-01-01 10:00:00'
	    t.time     "sunday_end",                    :default => '2000-01-01 18:00:00'
	    t.boolean  "monday_send",                   :default => true
	    t.time     "monday_start",                  :default => '2000-01-01 09:00:00'
	    t.time     "monday_end",                    :default => '2000-01-01 20:00:00'
	    t.boolean  "tuesday_send",                  :default => true
	    t.time     "tuesday_start",                 :default => '2000-01-01 09:00:00'
	    t.time     "tuesday_end",                   :default => '2000-01-01 20:00:00'
	    t.boolean  "wednesday_send",                :default => true
	    t.time     "wednesday_start",               :default => '2000-01-01 09:00:00'
	    t.time     "wednesday_end",                 :default => '2000-01-01 20:00:00'
	    t.boolean  "thursday_send",                 :default => true
	    t.time     "thursday_start",                :default => '2000-01-01 09:00:00'
	    t.time     "thursday_end",                  :default => '2000-01-01 20:00:00'
	    t.boolean  "friday_send",                   :default => true
	    t.time     "friday_start",                  :default => '2000-01-01 09:00:00'
	    t.time     "friday_end",                    :default => '2000-01-01 20:00:00'
	    t.boolean  "saturday_send",                 :default => true
	    t.time     "saturday_start",                :default => '2000-01-01 10:00:00'
	    t.time     "saturday_end",                  :default => '2000-01-01 18:00:00'
	  
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/preferences/edit.html.erb
<h1>Messaging Preference</h1>

<%= render 'form' %>

<%= link_to 'Show', @preference %> |
<%= link_to 'Back', preferences_path %>

app/views/preferences/edit1.html.erb
<%= semantic_form_for @preference do |f| %>
  <%= f.inputs do %>
    <%= f.input :voice %>
    <%= f.input :text %>
    <%= f.input :email %>
  
	<%= f.select :msg_pref, [['Send All Message Types','all'],['Send Just Texts','text'],['Send Just Voice Calls','voice'],['Send Just Emails','email']] %>
	
	  
<%= f.label :timezone %>
	
<%= f.collection_select :timezone, ActiveSupport::TimeZone.us_zones, :name, :to_s %>

app/views/preferences/index.html.erb
<h1><b>Settings</b></h1>
<br>

<ul class="nav nav-tabs">
  <li class="active"><a href="pages/controls"><h5>Controls</h5></a>
  </li>
  <li><a href="Message Times & Dates"><h5>Message Times & Dates</h5></a></li>
  <li><a href="pages/manage_users"><h5>Manage Users</h5></a></li>
  <li><a href="pages/staff_notifications"><h5>Staff Notifications</h5></a></li>
</ul>
<table>
  <tr>
    <th>Voice</th>
    <th>Text</th>
    <th>Email</th>
    <th>Messaging Preferences</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @preferences.each do |preference| %>
  <tr>
    <td><%= preference.voice %></td>
    <td><%= preference.text %></td>
    <td><%= preference.email %></td>
    <td><%= preference.msg_pref %></td>
    <td><%= link_to 'Show', preference %></td>
    <td><%= link_to 'Edit', edit_preference_path(preference) %></td>
	<td><%= link_to 'Edit1', edit_preference_path(preference) %></td>
    <td><%= link_to 'Delete', preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Preference', new_preference_path %>

app/views/preferences/message_times.html.erb
<h1>New preference</h1>

<%= render 'form' %>

<%= link_to 'Back', preferences_path %>

app/views/preferences/new.html.erb
<h1>New preference</h1>

<%= semantic_form_for @preference do |f| %>
  <%= f.inputs do %>
    <%= f.input :voice %>
    <%= f.input :text %>
    <%= f.input :email %>
  
	<%= f.select :msg_pref, [['Send All Message Types','all'],['Send Just Texts','text'],['Send Just Voice Calls','voice'],['Send Just Emails','email']] %>
	
	  
	
	    <%= f.label :timezone %>
	
		<%= f.collection_select :timezone, ActiveSupport::TimeZone.us_zones, :name, :to_s %>
	  
		<h3>Selet Do Not Contact days of the year</h3>
	   
	    <%= f.input :holiday_new_year %> 
	    <%= f.input :holiday_martin_luther_king_jr %> 
	    <%= f.input :holiday_presidents %> 
	    <%= f.input :holiday_memorial %> 
	    <%= f.input :holiday_independence %> 
	    <%= f.input :holiday_labor %> 
	    <%= f.input :holiday_columbus %> 
	    <%= f.input :holiday_veterans %> 
	    <%= f.input :holiday_thanksgiving %> 
	    <%= f.input :holiday_christmas %> 
	  
	    t.date     "added_holiday_1"
	    t.date     "added_holiday_2"
	    t.date     "added_holiday_3"
	    t.date     "added_holiday_4"
	    t.date     "added_holiday_5"
	    t.date     "added_holiday_6"
	    t.date     "added_holiday_7"
	    t.boolean  "sunday_send",                   :default => true
	    t.time     "sunday_start",                  :default => '2000-01-01 10:00:00'
	    t.time     "sunday_end",                    :default => '2000-01-01 18:00:00'
	    t.boolean  "monday_send",                   :default => true
	    t.time     "monday_start",                  :default => '2000-01-01 09:00:00'
	    t.time     "monday_end",                    :default => '2000-01-01 20:00:00'
	    t.boolean  "tuesday_send",                  :default => true
	    t.time     "tuesday_start",                 :default => '2000-01-01 09:00:00'
	    t.time     "tuesday_end",                   :default => '2000-01-01 20:00:00'
	    t.boolean  "wednesday_send",                :default => true
	    t.time     "wednesday_start",               :default => '2000-01-01 09:00:00'
	    t.time     "wednesday_end",                 :default => '2000-01-01 20:00:00'
	    t.boolean  "thursday_send",                 :default => true
	    t.time     "thursday_start",                :default => '2000-01-01 09:00:00'
	    t.time     "thursday_end",                  :default => '2000-01-01 20:00:00'
	    t.boolean  "friday_send",                   :default => true
	    t.time     "friday_start",                  :default => '2000-01-01 09:00:00'
	    t.time     "friday_end",                    :default => '2000-01-01 20:00:00'
	    t.boolean  "saturday_send",                 :default => true
	    t.time     "saturday_start",                :default => '2000-01-01 10:00:00'
	    t.time     "saturday_end",                  :default => '2000-01-01 18:00:00'
	  
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Voice:</b>
  <%= @preference.voice %>
</p>

<p>
  <b>Text:</b>
  <%= @preference.text %>
</p>

<p>
  <b>Email:</b>
  <%= @preference.email %>
</p>

<p>
  <b>Msg pref:</b>
  <%= @preference.msg_pref %>
</p>


<%= link_to 'Edit', edit_preference_path(@preference) %> |
<%= link_to 'Back', preferences_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<h1>Hello, Rails!</h1>



			

					<h1><b>Settings</b></h1>
					<br>

					<ul class="nav nav-tabs">
					  <li class="active"><a href="pages/controls"><h5>Controls</h5></a>
					  </li>
					  <li><a href="Message Times & Dates"><h5>Message Times & Dates</h5></a></li>
					  <li><a href="pages/manage_users"><h5>Manage Users</h5></a></li>
					  <li><a href="pages/staff_notifications"><h5>Staff Notifications</h5></a></li>
					</ul>
					<table>
					  <tr>
					    <th>Voice</th>
					    <th>Text</th>
					    <th>Email</th>
					    <th>Messaging Preferences</th>
					    <th></th>
					    <th></th>
					    <th></th>
					  </tr>